version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_sqlite
    ports:
      - "3000:3000"
    volumes:
      - ./data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    restart: always


